/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AdharAccordion {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharAvatar {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharBadge {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharButton {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharCard {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharCheckbox {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharDialog {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharDivider {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharDropdown {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharField {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharInfo {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharInput {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharLabel {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharLink {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharMenu {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharMessage {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharPersona {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharPopover {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharProgress {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharRadio {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharSkeleton {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharSlider {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharSpinner {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharSwitch {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharTab {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharTextarea {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharToast {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharToolbar {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AdharTooltip {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLAdharAccordionElement extends Components.AdharAccordion, HTMLStencilElement {
    }
    var HTMLAdharAccordionElement: {
        prototype: HTMLAdharAccordionElement;
        new (): HTMLAdharAccordionElement;
    };
    interface HTMLAdharAvatarElement extends Components.AdharAvatar, HTMLStencilElement {
    }
    var HTMLAdharAvatarElement: {
        prototype: HTMLAdharAvatarElement;
        new (): HTMLAdharAvatarElement;
    };
    interface HTMLAdharBadgeElement extends Components.AdharBadge, HTMLStencilElement {
    }
    var HTMLAdharBadgeElement: {
        prototype: HTMLAdharBadgeElement;
        new (): HTMLAdharBadgeElement;
    };
    interface HTMLAdharButtonElement extends Components.AdharButton, HTMLStencilElement {
    }
    var HTMLAdharButtonElement: {
        prototype: HTMLAdharButtonElement;
        new (): HTMLAdharButtonElement;
    };
    interface HTMLAdharCardElement extends Components.AdharCard, HTMLStencilElement {
    }
    var HTMLAdharCardElement: {
        prototype: HTMLAdharCardElement;
        new (): HTMLAdharCardElement;
    };
    interface HTMLAdharCheckboxElement extends Components.AdharCheckbox, HTMLStencilElement {
    }
    var HTMLAdharCheckboxElement: {
        prototype: HTMLAdharCheckboxElement;
        new (): HTMLAdharCheckboxElement;
    };
    interface HTMLAdharDialogElement extends Components.AdharDialog, HTMLStencilElement {
    }
    var HTMLAdharDialogElement: {
        prototype: HTMLAdharDialogElement;
        new (): HTMLAdharDialogElement;
    };
    interface HTMLAdharDividerElement extends Components.AdharDivider, HTMLStencilElement {
    }
    var HTMLAdharDividerElement: {
        prototype: HTMLAdharDividerElement;
        new (): HTMLAdharDividerElement;
    };
    interface HTMLAdharDropdownElement extends Components.AdharDropdown, HTMLStencilElement {
    }
    var HTMLAdharDropdownElement: {
        prototype: HTMLAdharDropdownElement;
        new (): HTMLAdharDropdownElement;
    };
    interface HTMLAdharFieldElement extends Components.AdharField, HTMLStencilElement {
    }
    var HTMLAdharFieldElement: {
        prototype: HTMLAdharFieldElement;
        new (): HTMLAdharFieldElement;
    };
    interface HTMLAdharInfoElement extends Components.AdharInfo, HTMLStencilElement {
    }
    var HTMLAdharInfoElement: {
        prototype: HTMLAdharInfoElement;
        new (): HTMLAdharInfoElement;
    };
    interface HTMLAdharInputElement extends Components.AdharInput, HTMLStencilElement {
    }
    var HTMLAdharInputElement: {
        prototype: HTMLAdharInputElement;
        new (): HTMLAdharInputElement;
    };
    interface HTMLAdharLabelElement extends Components.AdharLabel, HTMLStencilElement {
    }
    var HTMLAdharLabelElement: {
        prototype: HTMLAdharLabelElement;
        new (): HTMLAdharLabelElement;
    };
    interface HTMLAdharLinkElement extends Components.AdharLink, HTMLStencilElement {
    }
    var HTMLAdharLinkElement: {
        prototype: HTMLAdharLinkElement;
        new (): HTMLAdharLinkElement;
    };
    interface HTMLAdharMenuElement extends Components.AdharMenu, HTMLStencilElement {
    }
    var HTMLAdharMenuElement: {
        prototype: HTMLAdharMenuElement;
        new (): HTMLAdharMenuElement;
    };
    interface HTMLAdharMessageElement extends Components.AdharMessage, HTMLStencilElement {
    }
    var HTMLAdharMessageElement: {
        prototype: HTMLAdharMessageElement;
        new (): HTMLAdharMessageElement;
    };
    interface HTMLAdharPersonaElement extends Components.AdharPersona, HTMLStencilElement {
    }
    var HTMLAdharPersonaElement: {
        prototype: HTMLAdharPersonaElement;
        new (): HTMLAdharPersonaElement;
    };
    interface HTMLAdharPopoverElement extends Components.AdharPopover, HTMLStencilElement {
    }
    var HTMLAdharPopoverElement: {
        prototype: HTMLAdharPopoverElement;
        new (): HTMLAdharPopoverElement;
    };
    interface HTMLAdharProgressElement extends Components.AdharProgress, HTMLStencilElement {
    }
    var HTMLAdharProgressElement: {
        prototype: HTMLAdharProgressElement;
        new (): HTMLAdharProgressElement;
    };
    interface HTMLAdharRadioElement extends Components.AdharRadio, HTMLStencilElement {
    }
    var HTMLAdharRadioElement: {
        prototype: HTMLAdharRadioElement;
        new (): HTMLAdharRadioElement;
    };
    interface HTMLAdharSkeletonElement extends Components.AdharSkeleton, HTMLStencilElement {
    }
    var HTMLAdharSkeletonElement: {
        prototype: HTMLAdharSkeletonElement;
        new (): HTMLAdharSkeletonElement;
    };
    interface HTMLAdharSliderElement extends Components.AdharSlider, HTMLStencilElement {
    }
    var HTMLAdharSliderElement: {
        prototype: HTMLAdharSliderElement;
        new (): HTMLAdharSliderElement;
    };
    interface HTMLAdharSpinnerElement extends Components.AdharSpinner, HTMLStencilElement {
    }
    var HTMLAdharSpinnerElement: {
        prototype: HTMLAdharSpinnerElement;
        new (): HTMLAdharSpinnerElement;
    };
    interface HTMLAdharSwitchElement extends Components.AdharSwitch, HTMLStencilElement {
    }
    var HTMLAdharSwitchElement: {
        prototype: HTMLAdharSwitchElement;
        new (): HTMLAdharSwitchElement;
    };
    interface HTMLAdharTabElement extends Components.AdharTab, HTMLStencilElement {
    }
    var HTMLAdharTabElement: {
        prototype: HTMLAdharTabElement;
        new (): HTMLAdharTabElement;
    };
    interface HTMLAdharTextareaElement extends Components.AdharTextarea, HTMLStencilElement {
    }
    var HTMLAdharTextareaElement: {
        prototype: HTMLAdharTextareaElement;
        new (): HTMLAdharTextareaElement;
    };
    interface HTMLAdharToastElement extends Components.AdharToast, HTMLStencilElement {
    }
    var HTMLAdharToastElement: {
        prototype: HTMLAdharToastElement;
        new (): HTMLAdharToastElement;
    };
    interface HTMLAdharToolbarElement extends Components.AdharToolbar, HTMLStencilElement {
    }
    var HTMLAdharToolbarElement: {
        prototype: HTMLAdharToolbarElement;
        new (): HTMLAdharToolbarElement;
    };
    interface HTMLAdharTooltipElement extends Components.AdharTooltip, HTMLStencilElement {
    }
    var HTMLAdharTooltipElement: {
        prototype: HTMLAdharTooltipElement;
        new (): HTMLAdharTooltipElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "adhar-accordion": HTMLAdharAccordionElement;
        "adhar-avatar": HTMLAdharAvatarElement;
        "adhar-badge": HTMLAdharBadgeElement;
        "adhar-button": HTMLAdharButtonElement;
        "adhar-card": HTMLAdharCardElement;
        "adhar-checkbox": HTMLAdharCheckboxElement;
        "adhar-dialog": HTMLAdharDialogElement;
        "adhar-divider": HTMLAdharDividerElement;
        "adhar-dropdown": HTMLAdharDropdownElement;
        "adhar-field": HTMLAdharFieldElement;
        "adhar-info": HTMLAdharInfoElement;
        "adhar-input": HTMLAdharInputElement;
        "adhar-label": HTMLAdharLabelElement;
        "adhar-link": HTMLAdharLinkElement;
        "adhar-menu": HTMLAdharMenuElement;
        "adhar-message": HTMLAdharMessageElement;
        "adhar-persona": HTMLAdharPersonaElement;
        "adhar-popover": HTMLAdharPopoverElement;
        "adhar-progress": HTMLAdharProgressElement;
        "adhar-radio": HTMLAdharRadioElement;
        "adhar-skeleton": HTMLAdharSkeletonElement;
        "adhar-slider": HTMLAdharSliderElement;
        "adhar-spinner": HTMLAdharSpinnerElement;
        "adhar-switch": HTMLAdharSwitchElement;
        "adhar-tab": HTMLAdharTabElement;
        "adhar-textarea": HTMLAdharTextareaElement;
        "adhar-toast": HTMLAdharToastElement;
        "adhar-toolbar": HTMLAdharToolbarElement;
        "adhar-tooltip": HTMLAdharTooltipElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface AdharAccordion {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharAvatar {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharBadge {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharButton {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharCard {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharCheckbox {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharDialog {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharDivider {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharDropdown {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharField {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharInfo {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharInput {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharLabel {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharLink {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharMenu {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharMessage {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharPersona {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharPopover {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharProgress {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharRadio {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharSkeleton {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharSlider {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharSpinner {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharSwitch {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharTab {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharTextarea {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharToast {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharToolbar {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AdharTooltip {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "adhar-accordion": AdharAccordion;
        "adhar-avatar": AdharAvatar;
        "adhar-badge": AdharBadge;
        "adhar-button": AdharButton;
        "adhar-card": AdharCard;
        "adhar-checkbox": AdharCheckbox;
        "adhar-dialog": AdharDialog;
        "adhar-divider": AdharDivider;
        "adhar-dropdown": AdharDropdown;
        "adhar-field": AdharField;
        "adhar-info": AdharInfo;
        "adhar-input": AdharInput;
        "adhar-label": AdharLabel;
        "adhar-link": AdharLink;
        "adhar-menu": AdharMenu;
        "adhar-message": AdharMessage;
        "adhar-persona": AdharPersona;
        "adhar-popover": AdharPopover;
        "adhar-progress": AdharProgress;
        "adhar-radio": AdharRadio;
        "adhar-skeleton": AdharSkeleton;
        "adhar-slider": AdharSlider;
        "adhar-spinner": AdharSpinner;
        "adhar-switch": AdharSwitch;
        "adhar-tab": AdharTab;
        "adhar-textarea": AdharTextarea;
        "adhar-toast": AdharToast;
        "adhar-toolbar": AdharToolbar;
        "adhar-tooltip": AdharTooltip;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "adhar-accordion": LocalJSX.AdharAccordion & JSXBase.HTMLAttributes<HTMLAdharAccordionElement>;
            "adhar-avatar": LocalJSX.AdharAvatar & JSXBase.HTMLAttributes<HTMLAdharAvatarElement>;
            "adhar-badge": LocalJSX.AdharBadge & JSXBase.HTMLAttributes<HTMLAdharBadgeElement>;
            "adhar-button": LocalJSX.AdharButton & JSXBase.HTMLAttributes<HTMLAdharButtonElement>;
            "adhar-card": LocalJSX.AdharCard & JSXBase.HTMLAttributes<HTMLAdharCardElement>;
            "adhar-checkbox": LocalJSX.AdharCheckbox & JSXBase.HTMLAttributes<HTMLAdharCheckboxElement>;
            "adhar-dialog": LocalJSX.AdharDialog & JSXBase.HTMLAttributes<HTMLAdharDialogElement>;
            "adhar-divider": LocalJSX.AdharDivider & JSXBase.HTMLAttributes<HTMLAdharDividerElement>;
            "adhar-dropdown": LocalJSX.AdharDropdown & JSXBase.HTMLAttributes<HTMLAdharDropdownElement>;
            "adhar-field": LocalJSX.AdharField & JSXBase.HTMLAttributes<HTMLAdharFieldElement>;
            "adhar-info": LocalJSX.AdharInfo & JSXBase.HTMLAttributes<HTMLAdharInfoElement>;
            "adhar-input": LocalJSX.AdharInput & JSXBase.HTMLAttributes<HTMLAdharInputElement>;
            "adhar-label": LocalJSX.AdharLabel & JSXBase.HTMLAttributes<HTMLAdharLabelElement>;
            "adhar-link": LocalJSX.AdharLink & JSXBase.HTMLAttributes<HTMLAdharLinkElement>;
            "adhar-menu": LocalJSX.AdharMenu & JSXBase.HTMLAttributes<HTMLAdharMenuElement>;
            "adhar-message": LocalJSX.AdharMessage & JSXBase.HTMLAttributes<HTMLAdharMessageElement>;
            "adhar-persona": LocalJSX.AdharPersona & JSXBase.HTMLAttributes<HTMLAdharPersonaElement>;
            "adhar-popover": LocalJSX.AdharPopover & JSXBase.HTMLAttributes<HTMLAdharPopoverElement>;
            "adhar-progress": LocalJSX.AdharProgress & JSXBase.HTMLAttributes<HTMLAdharProgressElement>;
            "adhar-radio": LocalJSX.AdharRadio & JSXBase.HTMLAttributes<HTMLAdharRadioElement>;
            "adhar-skeleton": LocalJSX.AdharSkeleton & JSXBase.HTMLAttributes<HTMLAdharSkeletonElement>;
            "adhar-slider": LocalJSX.AdharSlider & JSXBase.HTMLAttributes<HTMLAdharSliderElement>;
            "adhar-spinner": LocalJSX.AdharSpinner & JSXBase.HTMLAttributes<HTMLAdharSpinnerElement>;
            "adhar-switch": LocalJSX.AdharSwitch & JSXBase.HTMLAttributes<HTMLAdharSwitchElement>;
            "adhar-tab": LocalJSX.AdharTab & JSXBase.HTMLAttributes<HTMLAdharTabElement>;
            "adhar-textarea": LocalJSX.AdharTextarea & JSXBase.HTMLAttributes<HTMLAdharTextareaElement>;
            "adhar-toast": LocalJSX.AdharToast & JSXBase.HTMLAttributes<HTMLAdharToastElement>;
            "adhar-toolbar": LocalJSX.AdharToolbar & JSXBase.HTMLAttributes<HTMLAdharToolbarElement>;
            "adhar-tooltip": LocalJSX.AdharTooltip & JSXBase.HTMLAttributes<HTMLAdharTooltipElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
